# Generated by Django 6.0.6 on 2026-09-25 17:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


def backfill_subtotal(apps, schema_editor):
    """Orders placed before discounts existed: subtotal = total, no discount."""
    Order = apps.get_model("orders", "Order")
    Order.objects.update(subtotal=models.F("total"))


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_address'),
        ('products', '0003_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.RunPython(backfill_subtotal, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9-]+$', 'Use only letters, digits, and hyphens.')])),
                ('kind', models.CharField(choices=[('PERCENT', 'Percent off'), ('FIXED', 'Fixed amount off')], default='PERCENT', max_length=7)),
                ('value', models.DecimalField(decimal_places=2, help_text='A percentage (1–100) or a dollar amount.', max_digits=10)),
                ('scope', models.CharField(choices=[('ORDER', 'Whole order'), ('PRODUCTS', 'Specific products')], default='ORDER', max_length=8)),
                ('expires_on', models.DateField(blank=True, help_text='Optional. The code works through the end of this date.', null=True, verbose_name='Expires on')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('products', models.ManyToManyField(blank=True, help_text='Only these products are discounted (specific-products codes).', related_name='discount_codes', to='products.product')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.discountcode'),
        ),
        migrations.AddConstraint(
            model_name='discountcode',
            constraint=models.CheckConstraint(condition=models.Q(('value__gt', 0)), name='discount_value_positive'),
        ),
        migrations.AddConstraint(
            model_name='discountcode',
            constraint=models.CheckConstraint(condition=models.Q(('kind', 'FIXED'), ('value__lte', 100), _connector='OR'), name='discount_percent_at_most_100'),
        ),
    ]
